# Generated by Django 4.2.30 on 2026-04-21 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(help_text='Short code used in barcode prefix, e.g. RLF', max_length=10, unique=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('buy_price', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('sell_price', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('alert_threshold', models.PositiveIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=100, unique=True)),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('UNIQUE', 'Taille unique')], max_length=10)),
                ('status', models.CharField(choices=[('in_stock', 'En stock'), ('in_order', 'Dans un ordre'), ('shipped', 'Expédié'), ('returned', 'Retourné')], default='in_stock', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bordereau_barcode', models.CharField(max_length=255, unique=True)),
                ('shipping_company', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('closed', 'Fermé')], default='open', max_length=10)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('received', 'Réception'), ('shipped', 'Expédition'), ('returned', 'Retour')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('moved_at', models.DateTimeField(auto_now_add=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.productunit')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(help_text='e.g. RED, GRN, BLU — used in barcode', max_length=50)),
                ('color_label', models.CharField(help_text='Display name, e.g. Rouge, Vert, Bleu', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='variants/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='inventory.product')),
            ],
            options={
                'unique_together': {('product', 'color_name')},
            },
        ),
        migrations.AddField(
            model_name='productunit',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='inventory.productvariant'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.shippingorder')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='inventory.productunit')),
            ],
            options={
                'unique_together': {('order', 'unit')},
            },
        ),
    ]
