# Generated by Django 6.0.4 on 2026-04-21 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingorder',
            name='amount_collected',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Actual amount collected from client', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shippingorder',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shippingorder',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingorder',
            name='payment_barcode',
            field=models.CharField(blank=True, help_text='Barcode from shipping company payment slip', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='status',
            field=models.CharField(choices=[('in_stock', 'En stock'), ('in_order', 'Dans un ordre'), ('shipped', 'Expédié'), ('sold', 'Vendu'), ('pending_return', 'Retour en attente'), ('returned', 'Retourné')], default='in_stock', max_length=20),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color_label',
            field=models.CharField(help_text='Display name e.g. Rouge', max_length=50),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color_name',
            field=models.CharField(help_text='e.g. RED, GRN, BLU', max_length=50),
        ),
        migrations.AlterField(
            model_name='shippingorder',
            name='status',
            field=models.CharField(choices=[('open', 'Ouvert'), ('closed', 'Fermé'), ('paid', 'Payé')], default='open', max_length=10),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('received', 'Réception'), ('shipped', 'Expédition'), ('sold', 'Vendu'), ('pending_return', 'Retour en attente'), ('returned', 'Retour physique')], max_length=20),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_barcode', models.CharField(blank=True, max_length=255)),
                ('amount_expected', models.DecimalField(decimal_places=3, max_digits=10)),
                ('amount_collected', models.DecimalField(decimal_places=3, max_digits=10)),
                ('shipping_fee', models.DecimalField(decimal_places=3, default=7, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='inventory.shippingorder')),
            ],
        ),
    ]
