# Generated by Django 6.0.4 on 2026-04-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_shippingorder_amount_collected_shippingorder_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunit',
            name='size',
            field=models.CharField(help_text='Ex: S, M, XL, 40, 41, 1, 2, UNIQUE...', max_length=20),
        ),
    ]
