# Generated by Django 6.0.4 on 2026-04-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_productunit_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status_at_close',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status_at_payment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status_at_scan',
            field=models.CharField(blank=True, default='in_order', max_length=20),
        ),
    ]
