# Generated by Django 6.0.4 on 2026-04-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_orderitem_status_at_close_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunit',
            name='status',
            field=models.CharField(choices=[('in_stock', 'En stock'), ('shipped', 'Expédié'), ('paid', 'Payé'), ('returned', 'Retourné')], default='in_stock', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('received', 'Réception'), ('shipped', 'Expédition'), ('paid', 'Payé'), ('returned', 'Retour')], max_length=20),
        ),
    ]
