# Generated by Django 6.0.4 on 2026-04-25 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_productunit_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavexSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navex_status', models.CharField(blank=True, max_length=100)),
                ('navex_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('our_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('amount_match', models.BooleanField(null=True)),
                ('raw_response', models.TextField(blank=True)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navex_logs', to='inventory.shippingorder')),
            ],
            options={
                'ordering': ['-synced_at'],
            },
        ),
        migrations.CreateModel(
            name='SizeAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20)),
                ('threshold', models.PositiveIntegerField(default=3, help_text='Alert when stock drops below this number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_alerts', to='inventory.productvariant')),
            ],
            options={
                'unique_together': {('variant', 'size')},
            },
        ),
    ]
