# Generated by Django 6.0.4 on 2026-04-28 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_navexsynclog_sizealert'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('treated', models.BooleanField(default=False)),
                ('treated_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='inventory.shippingorder')),
            ],
        ),
    ]
