# Generated by Django 6.0.4 on 2026-04-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_orderverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingorder',
            name='client_address',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='shippingorder',
            name='client_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='shippingorder',
            name='client_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shippingorder',
            name='client_ville',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shippingorder',
            name='navex_designation',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
