# Generated by Django 6.0.4 on 2026-05-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_shippingorder_client_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingorder',
            name='status',
            field=models.CharField(choices=[('open', 'Ouvert'), ('closed', 'Fermé'), ('paid', 'Payé'), ('partial_paid', 'Partiellement payé'), ('returned', 'Retourné'), ('partial_returned', 'Partiellement retourné'), ('livre', 'Livré'), ('partial_livre', 'Partiellement livré')], default='open', max_length=20),
        ),
    ]
