# Generated by Django 6.0.4 on 2026-05-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_shippingorder_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanSessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bordereau_barcode', models.CharField(max_length=50)),
                ('designation', models.CharField(blank=True, default='', max_length=500)),
                ('unit_count', models.IntegerField(default=0)),
                ('is_correct', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('session_date', models.DateField()),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
    ]
