# Generated by Django 6.0.4 on 2026-05-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_scansessionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alert_disabled',
            field=models.BooleanField(default=False, help_text='Skip low-stock alerts for this product (still active otherwise)'),
        ),
        migrations.AddField(
            model_name='product',
            name='archived',
            field=models.BooleanField(default=False, help_text='Retired product — hidden from lists and emails, but scanning still works'),
        ),
    ]
