# Generated by Django 6.0.4 on 2026-05-07 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_customer_salespage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=150)),
                ('action', models.CharField(choices=[('login', 'Connexion'), ('logout', 'Déconnexion'), ('scan_shipping', 'Scan expédition'), ('scan_return', 'Scan retour'), ('scan_reception', 'Scan réception'), ('status_change', 'Changement de statut'), ('edit', 'Modification'), ('create', 'Création'), ('delete', 'Suppression'), ('navex_push', 'Push Navex'), ('navex_sync', 'Sync Navex'), ('payment', 'Paiement'), ('other', 'Autre')], default='other', max_length=30)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('target_unit_barcode', models.CharField(blank=True, default='', max_length=100)),
                ('target_order_barcode', models.CharField(blank=True, default='', max_length=100)),
                ('target_model', models.CharField(blank=True, default='', max_length=80)),
                ('target_id', models.CharField(blank=True, default='', max_length=50)),
                ('extra', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='inventory_a_created_e73148_idx'), models.Index(fields=['user', '-created_at'], name='inventory_a_user_id_922dec_idx'), models.Index(fields=['action', '-created_at'], name='inventory_a_action_4c2c92_idx')],
            },
        ),
    ]
