# Generated by Django 6.0.4 on 2026-05-07 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_backfill_user_profiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(blank=True, default='', max_length=120)),
                ('localite', models.CharField(blank=True, default='', max_length=120)),
                ('address', models.TextField(blank=True, default='')),
                ('delivery_fee', models.DecimalField(decimal_places=3, default=7, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=3, default=0, help_text='Computed: sum(line totals) + delivery_fee − discount', max_digits=10)),
                ('status', models.CharField(choices=[('non_confirmee', 'Non confirmée'), ('confirmee', 'Confirmée'), ('injoignable', 'Injoignable'), ('pas_serieux', 'Pas sérieux'), ('annulee', 'Annulée')], default='non_confirmee', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('bordereau_barcode', models.CharField(blank=True, default='', max_length=50)),
                ('pushed_to_navex_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('web_form', 'Saisie manuelle'), ('shopify', 'Shopify')], default='web_form', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='inventory.customer')),
                ('sales_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='inventory.salespage')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='inventory.region')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, default='', max_length=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=3, default=0, help_text="Snapshot of the product's sell_price at order creation", max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.productvariant')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created_at'], name='inventory_o_created_bd47f5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='inventory_o_status_71f30d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['bordereau_barcode'], name='inventory_o_bordere_71e66a_idx'),
        ),
    ]
