# Generated by Django 6.0.4 on 2026-05-07 17:00

# Data migration: seed the 24 Tunisian governorates.
# Safe — only INSERTs missing rows. Never updates or deletes existing ones.

from django.db import migrations


GOUVERNORATS = [
    "Ariana", "Béja", "Ben Arous", "Bizerte", "Gabès", "Gafsa",
    "Jendouba", "Kairouan", "Kasserine", "Kébili", "La Manouba",
    "LE Kef", "Mahdia", "Médenine", "Monastir", "Nabeul", "Sfax",
    "Sidi Bouzid", "Siliana", "Sousse", "Tataouine", "Tozeur",
    "Tunis", "Zaghouan",
]


def seed(apps, schema_editor):
    Region = apps.get_model("inventory", "Region")
    for name in GOUVERNORATS:
        Region.objects.get_or_create(name=name)


def unseed(apps, schema_editor):
    # Reversal does nothing — keep the seed even on rollback to preserve any
    # foreign keys that reference these rows.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_region_order_orderline_and_more'),
    ]

    operations = [
        migrations.RunPython(seed, unseed),
    ]
