# Generated by Django 6.0.4 on 2026-05-07 18:04

# Data migration: align our governorate spelling with Navex's official list.
# Navex uses "La Manouba" (one N). We had seeded "La Mannouba" (two Ns).
# This is an UPDATE on a single Region row — no FKs are affected (linked by id).
# Idempotent: safe to re-run.

from django.db import migrations


def fix_spelling(apps, schema_editor):
    Region = apps.get_model("inventory", "Region")
    Region.objects.filter(name="La Mannouba").update(name="La Manouba")


def revert_spelling(apps, schema_editor):
    # Reverse migration restores old spelling, in case rollback is needed.
    Region = apps.get_model("inventory", "Region")
    Region.objects.filter(name="La Manouba").update(name="La Mannouba")


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_offer_offerproduct_orderoffer_orderline_order_offer'),
    ]

    operations = [
        migrations.RunPython(fix_spelling, revert_spelling),
    ]
