# Generated by Django 6.0.4 on 2026-05-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_fix_manouba_spelling'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='navex_label_url',
            field=models.URLField(blank=True, default='', help_text='Print URL returned by Navex after successful push', max_length=500),
        ),
    ]
