# Generated by Django 6.0.4 on 2026-05-08 12:20

# Data migration: order #4 was successfully pushed to Navex on 2026-05-08
# (bordereau 918762425951) but our parser failed at the time and didn't save it.
# This migration retroactively attaches the bordereau and marks the order
# as Confirmée so it stops looking like it needs a push.
#
# Idempotent: only updates if the order exists AND has no bordereau yet
# AND the bordereau matches what Navex confirmed. Re-running does nothing.

from django.db import migrations
from django.utils import timezone


def backfill(apps, schema_editor):
    Order = apps.get_model("inventory", "Order")
    try:
        order = Order.objects.get(pk=4)
    except Order.DoesNotExist:
        return  # nothing to fix on this DB
    if order.bordereau_barcode:
        return  # already has one — leave alone
    order.bordereau_barcode = "918762425951"
    order.navex_label_url = "https://app.navex.tn/print/imprimer.php?id=5100&code=918762425951"
    order.pushed_to_navex_at = timezone.now()
    if order.status == "non_confirmee":
        order.status = "confirmee"
    order.save()


def revert(apps, schema_editor):
    pass  # do not undo on rollback


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_order_navex_label_url'),
    ]

    operations = [
        migrations.RunPython(backfill, revert),
    ]
