# Generated by Django 6.0.4 on 2026-05-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_fix_order_4_already_pushed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.CharField(blank=True, choices=[('', '—'), ('client', 'Client a annulé'), ('changement', 'Annulé pour changement'), ('rupture_stock', 'Rupture de stock')], default='', help_text="Raison de l'annulation (client / changement / rupture stock)", max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('non_confirmee', 'Non confirmée'), ('confirmee', 'Confirmée'), ('injoignable', 'Injoignable'), ('pas_serieux', 'Pas sérieux'), ('rappeler_plus_tard', 'Rappeler plus tard'), ('annulee', 'Annulée')], default='non_confirmee', max_length=30),
        ),
    ]
