# Generated by Django 6.0.4 on 2026-05-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_order_cancel_reason_order_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='navex_last_status',
            field=models.CharField(blank=True, default='', help_text="Statut Navex tel que retourné par leur API (ex: 'En cours', 'Livré', 'En magasin')", max_length=80),
        ),
        migrations.AddField(
            model_name='order',
            name='navex_last_status_raw',
            field=models.TextField(blank=True, default='', help_text='Réponse Navex complète au dernier sync (pour debug)'),
        ),
        migrations.AddField(
            model_name='order',
            name='navex_last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
