# Generated by Django 6.0.4 on 2026-05-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_order_navex_last_status_order_navex_last_status_raw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='navex_livreur',
            field=models.CharField(blank=True, default='', help_text='Nom du livreur / agence Navex', max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='navex_livreur_tel',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='navex_motif',
            field=models.CharField(blank=True, default='', help_text="Motif lié au statut Navex actuel (ex: 'Client non sérieux')", max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='navex_pre_etat',
            field=models.CharField(blank=True, default='', help_text='État précédent côté Navex', max_length=80),
        ),
    ]
