# Generated by Django 6.0.4 on 2026-05-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_alter_stockmovement_options_stockmovement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='season',
            field=models.CharField(choices=[('summer', 'Été'), ('winter', 'Hiver')], default='summer', help_text='Saison du produit — utilisée pour filtrer la liste des produits', max_length=10),
        ),
    ]
