# Generated by Django 6.0.4 on 2026-05-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0038_productunit_early_return'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='exchangereturnitem',
            new_name='inventory_e_exchang_04b9e9_idx',
            old_name='inventory_e_exchang_a7e8c6_idx',
        ),
        migrations.AlterField(
            model_name='exchangereturnitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
