# Generated by Django 6.0.4 on 2026-05-31 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0040_productunit_at_depot'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_psid',
            field=models.CharField(blank=True, db_index=True, default='', help_text='ID Messenger (PSID) du client. Sert à relier les conversations DM.', max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='conversation_text',
            field=models.TextField(blank=True, default='', help_text='Conversation Messenger capturée pour vérifier la commande. Supprimée après 10 jours.'),
        ),
        migrations.AddField(
            model_name='order',
            name='conversation_updated_at',
            field=models.DateTimeField(blank=True, help_text='Date de la dernière capture/mise à jour de la conversation.', null=True),
        ),
    ]
