# Generated by Django 6.0.4 on 2026-05-31 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0041_customer_customer_psid_order_conversation_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(help_text='Nom de la campagne (clé de synchronisation avec le Google Sheet).', max_length=200, unique=True)),
                ('spend', models.DecimalField(decimal_places=2, default=0, help_text='Dépense synchronisée depuis le Google Sheet (devise du compte).', max_digits=12)),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Dernière synchronisation de la dépense depuis le Sheet.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offer', models.ForeignKey(blank=True, help_text='Offre liée à cette publicité (une offre peut avoir plusieurs pubs).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads', to='inventory.offer')),
            ],
            options={
                'ordering': ['-spend'],
            },
        ),
    ]
