# Generated by Django 6.0.6 on 2026-06-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0044_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('non_confirmee', 'Non confirmée'), ('confirmee', 'Confirmée'), ('injoignable', 'Injoignable'), ('pas_serieux', 'Pas sérieux'), ('rappeler_plus_tard', 'Rappeler plus tard'), ('en_cours', 'En cours'), ('au_magasin', 'Au magasin'), ('retour_expediteur', 'Retour Expéditeur'), ('rtn_client_agence', 'Rtn client/agence'), ('livree', 'Livrée'), ('annulee', 'Annulée'), ('supprime_navex', 'Supprimé Navex')], default='non_confirmee', max_length=30),
        ),
    ]
