# Generated by Django 6.0.6 on 2026-06-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0045_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_collected',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Montant réellement encaissé (synchronisé depuis v1 lors du paiement Navex).', max_digits=10, null=True),
        ),
    ]
