# Generated by Django 6.0.6 on 2026-06-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0047_backfill_v2_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('non_confirmee', 'Non confirmée'), ('confirmee', 'Confirmée'), ('injoignable', 'Injoignable'), ('pas_serieux', 'Pas sérieux'), ('rappeler_plus_tard', 'Rappeler plus tard'), ('en_cours', 'En cours'), ('au_magasin', 'Au magasin'), ('returning', 'En retour'), ('returned', 'Retourné'), ('livree', 'Livrée'), ('payee', 'Payée'), ('annulee', 'Annulée'), ('supprime_navex', 'Supprimé Navex')], default='non_confirmee', max_length=30),
        ),
    ]
