# Generated by Django 6.0.6 on 2026-06-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0049_backfill_v2_payee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_note',
            field=models.CharField(blank=True, default='', help_text="Note/raison saisie lors d'un changement de statut (injoignable, rappeler, pas sérieux).", max_length=300),
        ),
    ]
