# Generated by Django 6.0.6 on 2026-06-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0050_order_status_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvertyConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(blank=True, default='', max_length=64)),
                ('store_name', models.CharField(blank=True, default='', max_length=200)),
                ('store_currency', models.CharField(blank=True, default='', max_length=10)),
                ('access_token', models.TextField(blank=True, default='')),
                ('refresh_token', models.TextField(blank=True, default='')),
                ('access_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='converty_order_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('web_form', 'Saisie manuelle'), ('shopify', 'Shopify'), ('converty', 'Converty')], default='web_form', max_length=20),
        ),
    ]
