# Generated by Django 6.0.6 on 2026-06-17 12:56

from django.db import migrations, models


def _backfill_names(apps, schema_editor):
    Order = apps.get_model("inventory", "Order")
    for o in Order.objects.select_related("customer").all().iterator():
        if not o.customer_name and o.customer_id and o.customer.name:
            o.customer_name = o.customer.name
            o.save(update_fields=["customer_name"])


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0052_customerhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.RunPython(_backfill_names, _noop),
    ]
