# Generated by Django 6.0.6 on 2026-06-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0053_order_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingorder',
            name='navex_paid_detected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
