# Generated by Django 6.0.6 on 2026-06-18 16:12

from django.db import migrations, models
import django.utils.timezone


def _backfill_delivered(apps, schema_editor):
    Order = apps.get_model("inventory", "Order")
    # For orders already delivered/paid, set delivered_at from the linked
    # ShippingOrder's paid_at if available, else the order's updated_at.
    for o in Order.objects.filter(status__in=["livree", "payee"]).iterator():
        if o.delivered_at:
            continue
        dt = None
        try:
            so = o.shipping_orders.exclude(paid_at__isnull=True).order_by("paid_at").first()
            if so and so.paid_at:
                dt = so.paid_at
        except Exception:
            dt = None
        if dt is None:
            dt = o.updated_at
        if dt:
            o.delivered_at = dt
            o.save(update_fields=["delivered_at"])


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0054_shippingorder_navex_paid_detected_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(_backfill_delivered, _noop),
    ]
