# Generated by Django 6.0.6 on 2026-06-19 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0055_order_delivered_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferPagePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_prices', to='inventory.offer')),
                ('sales_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_prices', to='inventory.salespage')),
            ],
            options={
                'unique_together': {('offer', 'sales_page')},
            },
        ),
    ]
