# Generated by Django 6.0.6 on 2026-06-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0056_offerpageprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price_override',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
