# Generated by Django 6.0.6 on 2026-06-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0057_order_price_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_note_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
