# Generated by Django 6.0.6 on 2026-06-22 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0058_order_status_note_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessengerConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(default='messenger', help_text='messenger / instagram', max_length=20)),
                ('page_id', models.CharField(blank=True, default='', max_length=64)),
                ('sender_id', models.CharField(db_index=True, help_text='PSID (page-scoped user id) of the customer.', max_length=64)),
                ('sender_name', models.CharField(blank=True, default='', max_length=200)),
                ('messages', models.JSONField(blank=True, default=list)),
                ('source_ad_id', models.CharField(blank=True, default='', max_length=120)),
                ('source_ad_ref', models.CharField(blank=True, default='', max_length=200)),
                ('source_campaign', models.CharField(blank=True, default='', max_length=200)),
                ('ctwa_clid', models.CharField(blank=True, default='', max_length=200)),
                ('extracted', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('extracted', 'Extrait'), ('confirmed', 'Confirmé'), ('ignored', 'Ignoré')], db_index=True, default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matched_ad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='inventory.ad')),
                ('pending_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messenger_conversations', to='inventory.order')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
