# Generated by Django 6.0.6 on 2026-06-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0059_messengerconversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='messengerconversation',
            name='auto_replied',
            field=models.BooleanField(default=False, help_text='Whether the one-time auto-reply was already sent.'),
        ),
    ]
