# Generated by Django 6.0.4 on 2026-08-31 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0072_order_is_angry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adofferlink',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='messengerconversation',
            name='gemini_enriched',
            field=models.BooleanField(default=False, help_text='Whether the deferred Gemini address/product pass has run.'),
        ),
    ]
