# Generated by Django 6.0.4 on 2026-09-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0077_seed_unifunl_heartbeat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appkeyvalue',
            name='value',
            field=models.TextField(blank=True, default=''),
        ),
    ]
