# Generated by Django 6.0.4 on 2026-09-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0078_alter_appkeyvalue_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='description',
            field=models.TextField(blank=True, default='', help_text="Description de l'offre (pour l'IA / Unifunl et l'affichage)."),
        ),
        migrations.AddField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, help_text="Photo représentative de l'offre.", null=True, upload_to='offers/'),
        ),
        migrations.AddField(
            model_name='offer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
