# Generated by Django 6.0.4 on 2026-09-05 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0079_offer_description_offer_image_offer_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(blank=True, default='', help_text="Code couleur de l'ensemble, ex: WHT", max_length=50)),
                ('color_label', models.CharField(blank=True, default='', help_text='Nom de la couleur affiché, ex: Blanc', max_length=50)),
                ('image', models.ImageField(upload_to='offers/')),
                ('sort', models.PositiveIntegerField(default=0)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory.offer')),
            ],
            options={
                'ordering': ['sort', 'id'],
            },
        ),
    ]
