# Generated by Django 6.0.4 on 2026-09-08 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0080_offerimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=64, unique=True)),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram')], default='facebook', max_length=20)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('token_encrypted', models.TextField(blank=True, default='')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the token expires (IG ~60 days). Null = long-lived / non-expiring.', null=True)),
                ('last_refreshed_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
