# Generated by Django 6.0.4 on 2026-09-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0081_metatoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='capture_product_confidence',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='capture_product_note',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
