# Generated by Django 6.0.4 on 2026-09-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0082_order_capture_product_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='category',
            field=models.CharField(blank=True, choices=[('pull', 'Pull'), ('pantalon', 'Pantalon'), ('veste', 'Veste'), ('hoodie', 'Hoodie'), ('ensemble', 'Ensemble'), ('espadrille', 'Espadrille'), ('claquette', 'Claquette'), ('sport', 'Sport')], default='', help_text="Type de produit — aide l'IA à retrouver le bon article.", max_length=20),
        ),
    ]
