# Generated by Django 6.0.4 on 2026-09-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0083_offer_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='season',
            field=models.CharField(blank=True, choices=[('summer', 'Été'), ('winter', 'Hiver')], default='', help_text="Saison — l'IA cherche d'abord par saison, puis par catégorie.", max_length=10),
        ),
    ]
