# Generated by Django 6.0.4 on 2026-09-12 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0084_offer_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='messengerconversation',
            name='identified_offer',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='messengerconversation',
            name='identified_sig',
            field=models.CharField(blank=True, default='', help_text='Signature of the image(s) the offer was identified from.', max_length=300),
        ),
    ]
